# Generated by Django 5.2.6 on 2025-09-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreSolicitante', models.CharField(max_length=150)),
                ('DocumentoIdentidad', models.CharField(max_length=50)),
                ('Correo', models.EmailField(max_length=254)),
                ('Telefono', models.IntegerField()),
                ('TipoSolicitud', models.CharField(choices=[('AC', 'Académica'), ('AD', 'Administrativa'), ('TE', 'Técnica'), ('OT', 'Otra')], default='OT', max_length=20)),
                ('Asunto', models.CharField(max_length=50)),
                ('Descripcion', models.TextField()),
                ('FechaSolicitud', models.DateField()),
                ('ArchivoAdjunto', models.FileField(blank=True, null=True, upload_to='solicitudes/')),
            ],
        ),
    ]
